os: linux
sudo: false
language: python

install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt

script:
  - nosetest tests

cache:
  - pip

branches:
  only:
    - master

notifications:
  email: false