os: linux
sudo: false
language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt

script:
  - nosetests tests

cache:
  - pip

branches:
  only:
    - master

notifications:
  email: false