appname: qaadmin
type: web

builds:
- name: qaadmin

service:
  user: root
  replicas: 1
  mountpoints:
  - host: qaadmin.gtapp.xyz
    path: /
    tlsSecret: gtapp-xyz-tls
  ports:
  - port: 80
    targetPort: 5000

  containers:
  - name: qaadmin
    tty: false               # whether allocate tty
    cpu:
      limit: "1"
    memory:
      limit: 512M
    ports:
    - containerPort: 5000
